wakeApp/Models/Channel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace wakeApp.Models
{
    public class Channel
    {
        public int Id { get; set; }
        [Display(Name = "Nome do Canal")]
        public string ChannelName { get; set; } = string.Empty;
        [Display(Name = "Subtitulo do Canal")]
        public string SubtitleChannel { get; set; } = string.Empty;
        [Display(Name = "Descrição do Canal")]
        public string ChannelDescription { get; set; } = string.Empty;
        [DataType(DataType.Date)]
        public DateTime CreatedChannel { get; set; }
        public string ImageBanner { get; set; } = string.Empty;
        public string IconChannel { get; set; } = string.Empty;
        public int CountFollows { get; set; }
        public int UserId { get; set; }
        public virtual User? User { get; set; }
        public List<PostVideo>? PostVideos { get; set; }
    }
}

wakeApp/Controllers/ChannelsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using wakeApp.Repositories;
using Newtonsoft.Json;
using wakeApp.Data;
using wakeApp.Models;
using wakeApp.Dtos;

namespace wakeApp.Controllers
{
    public class ChannelsController : Controller
    {
        HttpClient _httpClient = new HttpClient() { BaseAddress = new Uri("https://localhost:7099/api/") };
        private readonly IChannelsRepository _channelsRepository;
        private readonly IPostVideoRepository _postVideoRepository;
        private readonly IUsersRepository _usersRepository;
        ViewModel viewModel = new ViewModel();

        public ChannelsController(IChannelsRepository channelsRepository, IPostVideoRepository postVideoRepository, IUsersRepository usersRepository)
        {
            _channelsRepository = channelsRepository;
            _postVideoRepository = postVideoRepository;
            _usersRepository = usersRepository;
        }

        // GET: Channels
        public IActionResult Index()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            var channels = _channelsRepository.GetAllChannels();
            return View(channels);
        }

        // GET: Channels/Details/5
        public IActionResult Details(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();

            if (id == null)
            {
                return NotFound();
            }
            
            viewModel.ChannelDto = _channelsRepository.GetChannelById(id);
            viewModel.PostVideoDtos = _postVideoRepository.GetAllVideosPerChannel(id);
            viewModel.CountFollowers = _postVideoRepository.GetFollowersPerChannel(id);

            if (viewModel.ChannelDto.ChannelName == "")
            {
                return RedirectToAction(nameof(Create));
            }

            return View(viewModel);
        }

        /*
        public IActionResult Videos()
        {
            var id = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }
            List<PostVideo> posts = new List<PostVideo>();
            posts = _postVideoRepository.GetAllVideosPerChannel(id);

            if (posts == null)
            {
                return NotFound();
            }

            return View(posts);
        }
        */
        // GET: Channels/Create
        public IActionResult Create()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            return View();
        }

        // POST: Channels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,ChannelName,SubtitleChannel,ChannelDescription,CreatedChannel")] Channel channel, [Bind("BannerChannel")] IFormFile BannerChannel, [Bind("ChannelIcon")] IFormFile ChannelIcon)
        {
            channel = _channelsRepository.CreateChannel(channel, BannerChannel, ChannelIcon);
            return RedirectToAction(nameof(Details));
        }

        // GET: Channels/Edit/5
        public IActionResult Edit()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            var id = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var channel = _channelsRepository.GetChannelById(id);

            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Channels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,ChannelName,ChannelDescription")] Channel channel, [Bind("BannerImage")] IFormFile BannerImage)
        {
            if (id != channel.Id)
            {
                return NotFound();
            }

            channel = _channelsRepository.EditChannel(id, channel, BannerImage);

            if (channel == null)
            {
                return BadRequest();
            }

            return View(channel);
        }

        // GET: Channels/Delete/5
        public IActionResult Delete(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var channel = _channelsRepository.GetChannelById(id);

            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Channels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var channelReturn = _channelsRepository.DeleteChannel(id);

            if (channelReturn == false)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

wakeApp/Controllers/PostVideosController.cs
#nullable disable
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using wakeApp.Data;
using wakeApp.Models;
using wakeApp.Services;
using wakeApp.Repositories;
using wakeApp.Dtos;

namespace wakeApp.Controllers
{
    public class PostVideosController : Controller
    {
        HttpClient _httpClient = new HttpClient() { BaseAddress = new Uri("https://localhost:7099/api/") };
        private readonly IPostVideoRepository _repository;
        private readonly IUsersRepository _usersRepository;
        private readonly ICommentRepository _commentRepository;
        ViewModel viewModel = new ViewModel();
        public PostVideosController(IPostVideoRepository repository, IUsersRepository usersRepository, 
            ICommentRepository commentRepository)
        {
            _repository = repository;
            _usersRepository = usersRepository;
            _commentRepository = commentRepository;
        }
        // GET: PostVideos
        public IActionResult Index(string? searchString)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            viewModel.PostVideoDtos = _repository.GetAllVideos(searchString);

            if(viewModel.PostVideoDtos == null)
            {
                return View("Error");
            }
            
            return View(viewModel);
        }

        // GET: PostVideos/Details/5
        public ActionResult Details(int? id)
       {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            viewModel.PostVideoDto = _repository.GetPostVideo(id);
            viewModel.CountLike = _repository.GetLikesPerVideos(viewModel.PostVideoDto.Id);
            viewModel.CommentDtos = _commentRepository.GetCommentsPerVideos(viewModel.PostVideoDto.Id);
            viewModel.CountFollowers = _repository.GetFollowersPerChannel(viewModel.PostVideoDto.ChannelId);
            viewModel.UserId = _usersRepository.GetUserId();

            return View(viewModel);
        }

        // GET: PostVideos/Create
        public IActionResult Create()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            return View();
        }

        // POST: PostVideos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,Title,Description")] PostVideo postVideo, [Bind("FileVideo")] IFormFile FileVideo, [Bind("FileImage")] IFormFile FileImage)
        {
            var video = _repository.CreatePostVideo(postVideo, FileImage, FileVideo);

            if(video == null)
            {
                RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLike([Bind("Id,PostId,ChannelId,UserId")] EvaluationDto evaluation)
        {
            evaluation.CountLike = 1;
            var id = evaluation.PostId;
            evaluation = _repository.AddLike(evaluation);

            if (evaluation == null)
            {
                RedirectToAction(nameof(Index));
            }

            return Redirect("/PostVideos/Details/" + id);
        }

        // GET: PostVideos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var postVideo = _repository.GetPostVideo(id);

            if (postVideo == null)
            {
                return NotFound();
            }

            return View(postVideo);
        }

        // POST: PostVideos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description")] PostVideo postVideo, [Bind("FileVideo")] IFormFile FileVideo, [Bind("FileImage")] IFormFile FileImage)
        {
            var video = _repository.EditVideo(id, postVideo, FileVideo, FileImage);

            if (video == null)
            {
                RedirectToAction(nameof(Index));
            }

            return View(postVideo);
        }

        // GET: PostVideos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            if (id == null)
            {
                return NotFound();
            }

            var postVideo = _repository.GetPostVideo(id);

            if (postVideo == null)
            {
                return NotFound();
            }

            return View(postVideo);
        }

        // POST: PostVideos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var videoDelete = _repository.DeleteVideo(id);

            if (!videoDelete)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        //Comments
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateComment([Bind("Id,CommentText,UserId,ChannelId,PostId")] CommentDto commentDto)
        {
            commentDto.Flag = true;
            var id = commentDto.PostId;
            commentDto = _commentRepository.AddComment(commentDto);

            if (commentDto == null)
            {
                RedirectToAction(nameof(Index));
            }
            return Redirect("/PostVideos/Details/" + id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteComment(int idVideo, int idComment, int UserId)
        {
            if (idComment == 0 && UserId == 0)
            {
                return NotFound();
            }

            var postVideo = _commentRepository.DeleteComment(idComment, UserId);

            if (postVideo == false)
            {
                return NotFound();
            }

            return Redirect("/PostVideos/Details/" + idVideo);
        }
    }
}

wakeApp/Views/Channels/Create.cshtml
@model wakeApp.Models.Channel

@{
    ViewData["Title"] = "Create";
}


<div class="row justify-content-center">
    <div class="card col-md-6">
        <h3 class="text-center m-3">Criar Canal</h3>
        <hr />
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ChannelName" class="control-label text-black"></label>
                <input asp-for="ChannelName" class="form-control" />
                <span asp-validation-for="ChannelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubtitleChannel" class="control-label text-black"></label>
                <input asp-for="SubtitleChannel" class="form-control" />
                <span asp-validation-for="SubtitleChannel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChannelDescription" class="control-label text-black"></label>
                <input asp-for="ChannelDescription" class="form-control" />
                <span asp-validation-for="ChannelDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="BannerChannel" class="control-label label-file">
                    <i class="fa-solid fa-upload"></i>
                    <p>Upload Banner</p>
                </label>
                <input name="BannerChannel" type="file" class="form-control input-file" id="BannerChannel" />
                <span for="BannerChannel" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="ChannelIcon" class="control-label label-file">
                    <i class="fa-solid fa-upload"></i>
                    <p>Upload Icone</p>
                </label>
                <input name="ChannelIcon" type="file" class="form-control input-file" id="ChannelIcon" />
                <span for="ChannelIcon" class="text-danger"></span>
            </div>
            <div class="form-group text-center">
                <input type="submit" value="Enviar" class="btn btn-primary" />
            </div>
        </form>
        <div class="form-group text-center m-2">
            <a class="btn btn-danger" asp-controller="PostVideos" asp-action="Index">Back to List</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

wakeApp/Views/Channels/Delete.cshtml
@model wakeApp.Models.Channel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Channel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChannelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChannelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ChannelDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ChannelDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedChannel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedChannel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageBanner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageBanner)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

wakeApp/Views/Channels/Details.cshtml
@using wakeApp.Dtos
@model ViewModel

@{
    ViewData["Title"] = @Model.ChannelDto.ChannelName + " - ";
    ViewData["Follows"] = "Nenhum Inscrito";

}

<div>
    <div class="menu-channel">
        <div class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" style="height:250px;">
                    <img src="@Html.DisplayFor(model => model.ChannelDto.ImageBanner)" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>@Html.DisplayFor(model => model.ChannelDto.ChannelName)</h5>
                        <p>@Html.DisplayFor(model => model.ChannelDto.SubtitleChannel)</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="sub-menu-channel card-body" style="background-color: #131313;">
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <div class="" style="text-align:center;">
                        <img src="@Html.DisplayFor(model => model.ChannelDto.IconChannel)" style="width: 70px; ">
                        <h5 class="card-title" style="align-items:center;">@Html.DisplayFor(model => model.ChannelDto.ChannelName)</h5>
                        @if(Model.CountFollowers == 0)
                        {
                            @ViewData["Follows"]
                        }
                        else 
                        {
                            <p class="card-title" style="align-items:center;">
                                @Html.DisplayFor(model => model.CountFollowers) Inscritos
                            </p>
                        }
                    </div>
                    <!--
                    if (Model != null)
                    {
                        <a class="btn btn-primary d-flex" asp-action="Edit" asp-route-id="Model.Id">Customize Channel</a>
                    }
                    -->
                    @if (Model != null)
                    {
                     
                    }
                </div>
            </nav>
            <nav class="navbar navbar-expand-lg">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav nav-pills me-auto mb-2 mb-lg-0 nav-channel" id="pills-tab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-channel-link active" id="pills-videos-tab" data-bs-toggle="pill" data-bs-target="#pills-videos" role="tab">Videos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-channel-link" id="pills-live-tab" data-bs-toggle="pill" data-bs-target="#pills-live" role="tab">Lives</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-channel-link" id="pills-playlist-tab" data-bs-toggle="pill" data-bs-target="#pills-playlist" role="tab">Playlist</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-channel-link" id="pills-about-tab" data-bs-toggle="pill" data-bs-target="#pills-about" role="tab">Sobre</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-channel-link" id="pills-community-tab" data-bs-toggle="pill" data-bs-target="#pills-community" role="tab">Comunidade</a>
                            </li>
                        </ul>
                        <form class="d-flex">
                            <input class="form-control me-2 bg-dark" type="search" placeholder="Search" aria-label="Search">
                        </form>
                    </div>
                </div>
            </nav>
        </div>
    </div>

    <div class="tab-content" id="pills-tabContent" style="margin: 20px;">
        <div class="tab-pane fade show active" id="pills-videos" role="tabpanel" aria-labelledby="pills-videos-tab">
            @if (Model.PostVideoDtos != null)
            {
                @foreach (var item in Model.PostVideoDtos)
                {
                    <div class="card-1 d-inline-block" style="width: 18rem; margin: 6px;">
                        <a asp-controller="PostVideos" asp-action="Details" asp-route-id="@item.Id">
                            <img src="@Html.DisplayFor(modelItem => item.ThumbImage)" class="card-img-top" alt="...">
                            <div class="card-body">
                                <p class="card-text">@Html.DisplayFor(modelItem => item.Title)</p>
                            </div>
                        </a>
                    </div>
                }
            }
        </div>

        <div class="tab-pane fade" id="pills-live" role="tabpanel" aria-labelledby="pills-live-tab">
            <h4>Nenhum evento ao vivo.</h4>
        </div>

        <div class="tab-pane fade" id="pills-playlist" role="tabpanel" aria-labelledby="pills-about-tab">
            <h4>Ainda sem playlist</h4>
        </div>

        <div class="tab-pane fade" id="pills-about" role="tabpanel" aria-labelledby="pills-about-tab">
            <h4>@Html.DisplayFor(model => model.ChannelDto.ChannelDescription)</h4>
        </div>

        <div class="tab-pane fade" id="pills-community" role="tabpanel" aria-labelledby="pills-community-tab">
            <h4>Comments</h4>
            <form>
                <div class="row mb-3">
                    <div class="col-sm-6">
                        <input type="email" class="form-control" id="inputEmail3">
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Post</button>
            </form>
        </div>
    </div>

</div>

wakeApp/Views/Channels/Edit.cshtml
@model wakeApp.Models.Channel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Channel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ChannelName" class="control-label"></label>
                <input asp-for="ChannelName" class="form-control" />
                <span asp-validation-for="ChannelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChannelDescription" class="control-label"></label>
                <input asp-for="ChannelDescription" class="form-control" />
                <span asp-validation-for="ChannelDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="BannerChannel" class="control-label"></label>
                <input name="BannerChannel" type="file" class="form-control" />
                <span for="BannerChannel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

wakeApp/Views/Channels/Index.cshtml
@model IEnumerable<wakeApp.Models.Channel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ChannelName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChannelDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedChannel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageBanner)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChannelName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChannelDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedChannel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageBanner)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>