wakeApp/Controllers/ChannelsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using wakeApp.Repositories;
using Newtonsoft.Json;
using wakeApp.Data;
using wakeApp.Models;
using wakeApp.Dtos;

namespace wakeApp.Controllers
{
    public class ChannelsController : Controller
    {
        HttpClient _httpClient = new HttpClient() { BaseAddress = new Uri("https://localhost:7099/api/") };
        private readonly IChannelsRepository _channelsRepository;
        private readonly IPostVideoRepository _postVideoRepository;
        private readonly IUsersRepository _usersRepository;
        ViewModel viewModel = new ViewModel();

        public ChannelsController(IChannelsRepository channelsRepository, IPostVideoRepository postVideoRepository, IUsersRepository usersRepository)
        {
            _channelsRepository = channelsRepository;
            _postVideoRepository = postVideoRepository;
            _usersRepository = usersRepository;
        }

        // GET: Channels
        public IActionResult Index()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            var channels = _channelsRepository.GetAllChannels();
            return View(channels);
        }

        // GET: Channels/Details/5
        public IActionResult Details(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();

            if (id == null)
            {
                return NotFound();
            }
            
            viewModel.ChannelDto = _channelsRepository.GetChannelById(id);
            viewModel.PostVideoDtos = _postVideoRepository.GetAllVideosPerChannel(id);
            viewModel.CountFollowers = _postVideoRepository.GetFollowersPerChannel(id);

            if (viewModel.ChannelDto.ChannelName == "")
            {
                return RedirectToAction(nameof(Create));
            }

            return View(viewModel);
        }

        /*
        public IActionResult Videos()
        {
            var id = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }
            List<PostVideo> posts = new List<PostVideo>();
            posts = _postVideoRepository.GetAllVideosPerChannel(id);

            if (posts == null)
            {
                return NotFound();
            }

            return View(posts);
        }
        */
        // GET: Channels/Create
        public IActionResult Create()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            return View();
        }

        // POST: Channels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,ChannelName,SubtitleChannel,ChannelDescription,CreatedChannel")] Channel channel, [Bind("BannerChannel")] IFormFile BannerChannel, [Bind("ChannelIcon")] IFormFile ChannelIcon)
        {
            channel = _channelsRepository.CreateChannel(channel, BannerChannel, ChannelIcon);
            return RedirectToAction(nameof(Details));
        }

        // GET: Channels/Edit/5
        public IActionResult Edit()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            var id = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var channel = _channelsRepository.GetChannelById(id);

            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Channels/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,ChannelName,ChannelDescription")] Channel channel, [Bind("BannerImage")] IFormFile BannerImage)
        {
            if (id != channel.Id)
            {
                return NotFound();
            }

            channel = _channelsRepository.EditChannel(id, channel, BannerImage);

            if (channel == null)
            {
                return BadRequest();
            }

            return View(channel);
        }

        // GET: Channels/Delete/5
        public IActionResult Delete(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var channel = _channelsRepository.GetChannelById(id);

            if (channel == null)
            {
                return NotFound();
            }

            return View(channel);
        }

        // POST: Channels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var channelReturn = _channelsRepository.DeleteChannel(id);

            if (channelReturn == false)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

wakeApp/Controllers/UsersController.cs
#nullable disable
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using wakeApp.Data;
using wakeApp.Services;
using wakeApp.Repositories;
using wakeApp.Models;
using Newtonsoft.Json;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace wakeApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly wakeAppContext _context;
        HttpClient _httpClient = new HttpClient() { BaseAddress = new Uri("https://localhost:7099/api/") };
        private readonly IUsersRepository _usersRepository;

        public UsersController(wakeAppContext context, IUsersRepository usersRepository)
        {
            _context = context;
            _usersRepository = usersRepository;
        }

        // GET: Users
        public IActionResult Index()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            return RedirectToRoute(new { controller = "PostVideos", action = "Index"});
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var user = _usersRepository.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,UserName,FullName,Email,Password")] User user)
        {
            user = _usersRepository.CreateUser(user);
            return View(user);
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] 
        public ActionResult Login([Bind("UserName,Password")] UserLogin login )
        {
            var userLogin = _usersRepository.LoginUser(login);

            if (userLogin == false)
            {
                ViewBag.ErrorLogin = "Houve um erro!";
                return Redirect("/Users/Login");
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var user = _usersRepository.GetUserById(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,FullName,Email,Password")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            user = _usersRepository.EditUser(id, user);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [Authorize]
        public IActionResult Logoff()
        {
            _usersRepository.Logoff();
            return RedirectToRoute(new { controller = "PostVideos", action = "Index" });
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.NameLogin = _usersRepository.GetUserName();
            ViewBag.UseID = _usersRepository.GetUserId();
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = _usersRepository.DeleteUser(id);

            if (!user)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

wakeApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using wakeApp.Data
@using wakeApp.Models
@using Microsoft.AspNetCore.Mvc


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/png" href="~/src/icon.ico" sizes="32x32">
    <title>@ViewData["Title"] Wake</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/wakeApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PostVideos" asp-action="Index">
                    <img style="width: 40px;" src="~/src/IconWake.png" />  Wake
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">
                        <form class="d-md-flex border-1" asp-controller="PostVideos" asp-action="Index">
                            <input class="form-control me-0" style="width: 400px;" type="search" placeholder="Search" aria-label="Search" name="SearchString">
                        </form>
                    </ul>
                </div>
                <ul class="navbar-nav flex-row">
                    <li class="nav-item me-3 me-lg-1">
                        @if (@ViewBag.NameLogin != "")
                        {
                            <a class="nav-link" asp-controller="PostVideos" asp-action="Create">
                                <span>
                                    <i class="bi bi-plus-circle-fill"></i>
                                    <strong>New Vídeo</strong>
                                </span>
                            </a>

                        }
                    </li>
                    <li class="nav-item me-3 me-lg-1">
                    </li>
                    @if (@ViewBag.NameLogin == "")
                    {
                        <li class="nav-item me-3 me-lg-1">
                            <a class="nav-link" asp-controller="Users" asp-action="Create">
                                Sing-in
                            </a>
                        </li>
                        <li class="nav-item me-3 me-lg-1">
                            <a class="nav-link" asp-controller="Users" asp-action="Login"> Login</a>
                        </li>
                    }
                    @if (@ViewBag.NameLogin != "")
                    {
                        <li class="nav-item dropdown me-3 me-lg-1">
                            <a class="nav-link dropdown-toggle d-sm-flex align-items-sm-center" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                                @if (@ViewBag.NameLogin != "")
                                {
                                    <strong class="d-none d-sm-block ms-1">@ViewBag.NameLogin</strong>
                                }
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Channels" asp-action="Details" asp-route-id="@ViewBag.UseID">Meu Canal</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Users" asp-action="Details" asp-route-id="@ViewBag.UseID">
                                        Conta do Usuário
                                    </a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" asp-controller="Users" asp-action="Logoff">Logout</a></li>
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="">
        <main class="d-flex flex-nowrap" role="main">
            <div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark border-2" style="width: 280px;">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="/" class="nav-link text-white" aria-current="page">
                            <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home" /></svg>
                            <i class="bi bi-house-fill"></i> Inicio
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link text-white">
                            <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2" /></svg>
                            <i class="bi bi-skip-end-btn-fill"></i> Inscrições
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link text-white">
                            <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2" /></svg>
                            <i class="bi bi-camera-video-fill"></i> Lives
                        </a>
                    </li>
                </ul>
                <hr style="height:3px; background-color:lightgray;">
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="#" class="nav-link disabled text-white" aria-current="page">
                            <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home" /></svg>
                            <i class="bi bi-bookmark-check-fill"></i> Canais Inscritos
                        </a>
                    </li>
                </ul>
                <hr style="height:3px; background-color:lightgray;">
                <ul class="nav nav-pills flex-column mb-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link disabled text-white" aria-current="page">
                            <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home" /></svg>
                            <i class="bi bi-list-stars"></i> Categorias
                        </a>
                    </li>
                </ul>
            </div>
            <div class="d-block container">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2022 - wakeApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>